### ISSUE TITLE
Add link to the slide in the read me

### ISSUE THREAD

**Issue by adest** [sebastienblanc/devoxxfr#1]
Hello Seb,

Your talk @ DevoxxFR  was really cool, and the slides was very fun.
Can you please add a link to the slides in your read.me ?

Thank you in advance and see you soon at the Montpellier JUG :).
Regards.

**Comment by sebastienblanc** [comment]
I added the link to the slide deck I did for Snowcamp, it's the same as for Devoxx, even more slides ;) Thnaks for the kind words.
